name: "Release"

on:
  push:
    branches:
      - release

jobs:
  check-release-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Cargo.toml Version
        run: |
          if git diff HEAD^ HEAD -- src-tauri/Cargo.toml | grep -qE '^[-+]{1}version = "[0-9.]+"'; then
            echo "Cargo.toml version has been updated."
          else
            echo "Cargo.toml version has not been updated. Please update the version number in Cargo.toml."
            exit 1
          fi

  publish-tauri:
    needs: check-release-version
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-20.04, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/frontend-setup

      - name: Lint check frontend
        run: pnpm run lint-check

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: noter-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'Noter v__VERSION__'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: false
          prerelease: false